vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    user_avatar:
      uri_prefix: /media/users
      upload_destination: '%kernel.project_dir%/public/media/users'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true